/* Use Database and Schema*/
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;

CREATE OR REPLACE  VIEW CUSTOMER_VIEW AS
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY, JOIN_DATE
FROM CUSTOMER;

SELECT * from CUSTOMER_VIEW;

CREATE OR REPLACE VIEW CUSTOMER_LOCATION_VIEW AS
SELECT CUSTOMER_ID, CONCAT(ADDRESS, ', ', CITY, ', ', STATE, ', ', COUNTRY) AS LOCATION
FROM CUSTOMER;

SELECT * from CUSTOMER_LOCATION_VIEW;

-- Create a materialized view called CUSTOMER_LOCATION_MV

CREATE OR REPLACE  MATERIALIZED VIEW CUSTOMER_LOCATION_MV
AS
SELECT CUSTOMER_ID, CONCAT(ADDRESS, ', ', CITY, ', ', STATE, ', ', COUNTRY) AS LOCATION
FROM CUSTOMER
WHERE STATE = 'CA';

select * from CUSTOMER_LOCATION_MV;

-- Create a secure materialized view called CUSTOMER_LOCATION_MV
CREATE OR REPLACE SECURE MATERIALIZED VIEW CUSTOMER_LOCATION_MV_S
AS
SELECT CUSTOMER_ID, CONCAT(ADDRESS, ', ', CITY, ', ', STATE, ', ', COUNTRY) AS LOCATION
FROM CUSTOMER
WHERE STATE = 'CA';

-- Display all the views
SHOW VIEWS;

SELECT * from CUSTOMER_LOCATION_MV_S;


USE ROLE ACCOUNTADMIN;

--Grant relevant access on DB
GRANT USAGE on DATABASE LA_DB to USERADMIN;
-- Grant usage access on a schema
GRANT USAGE on SCHEMA LA_SCHEMA to USERADMIN;

-- Grant select access on views
GRANT SELECT on VIEW CUSTOMER_LOCATION_MV TO USERADMIN;
GRANT SELECT on VIEW CUSTOMER_LOCATION_MV_S TO USERADMIN;

-- Grant warehouse usage to the role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE USERADMIN;


-- change the role
USE ROLE USERADMIN;


--check DDL code
select get_ddl('view','CUSTOMER_LOCATION_MV_S'); --error due to secured Object does not exist, or operation cannot be performed.
select get_ddl('view','CUSTOMER_LOCATION_MV');

-- Run Select Queries
SELECT * from CUSTOMER_LOCATION_MV;
SELECT * from CUSTOMER_LOCATION_MV_S;
